title: Akshay Nagar # your name (or website title) here
logo: "/images/DP2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi I am a Spatial Data Scientist & Internationaly Licensed Architect & Real Estate & Urban Policy & Data Enthusiast
  <br><br>
  Architectural & Smart Cities Spatial Science Consultant
  <br>M. Urban Spatial Analytics , M.Arch(Assoc. AIA), BSc(Hons)Architecture(Riba Pt1)
  <br><br>
  <a href="https://www.linkedin.com/in/akshay-nagar-a595632a/">Please View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
